dullarjs/dullar

packages/mercury/examples/Content.vue, packages/mercury/examples/category-select/categorySelect.vue, packages/mercury/examples/router.js, packages/mercury/src/category-select/category-select.js, packages/mercury/src/category-select/index.js, packages/mercury/src/category-select/style/index.js, packages/mercury/src/category-select/style/index.less, packages/mercury/src/index.js, packages/mercury/src/index.less, packages/mercury/types/category-select.ts, packages/mercury/types/index.d.ts
=> feat: 分类选择器组件提交（category-select）

packages/earth/examples/dropdown-menu/dropdownMenu.vue, packages/earth/package-lock.json, packages/earth/src/dropdown-menu-item/dropdown-menu-item.js, packages/earth/src/dropdown-menu/dropdown-menu.js
=> Feature wangsz dropdown menu

packages/mercury/examples/table/table.vue, packages/mercury/src/table/style/index.less, packages/mercury/src/table/table.js
table组件添加loading、空数据提示、表头显隐功能，修复部分样式问题、搜索框定位等问题
=> fix: table组件添加loading、空数据提示、表头显隐功能，修复部分样式问题、搜索框定位等问题

packages/earth/examples/dropdown-menu/dropdownMenu.vue, packages/earth/src/dropdown-menu-item/dropdown-menu-item.js, packages/earth/src/dropdown-menu/dropdown-menu.js, packages/earth/src/dropdown-menu/style/index.less
dropdownMenu 1,展开选项增加下划线; 2，小箭头逻辑修复
=> Feature wangsz dropdown menu2

packages/mercury/examples/table/table.vue, packages/mercury/src/pagination/pagination.js, packages/mercury/src/table/table.js
=> fix:table支持直接渲染组件，分页缺陷修复

packages/earth/examples/city-picker/cityPicker.vue, packages/earth/examples/city-picker/ykb_hot_city.json, packages/earth/src/city-picker/city-picker.js
=> Feature wangsz city picker

packages/mercury/src/table/table.js
=> fix: table单选抛出数据错误

packages/earth/src/counter/style/index.less
=> fix: couter组件增加高亮非高亮辨识度

packages/earth/examples/dropdown-menu/dropdownMenu.vue, packages/earth/src/dropdown-menu-item/dropdown-menu-item.js
yn-dropdown-menu-item增加borderRadius属性
=> feat: yn-dropdown-menu-item增加borderRadius属性

packages/mercury/examples/pagination/pagination.vue, packages/mercury/src/pagination/pagination.js, packages/mercury/src/pagination/style/index.less
=> fix:pagination组件-字体ui调整以及优化

packages/earth/examples/toast/toast.vue, packages/earth/src/toast/toast.js
=> feat: toast默认居中展示

packages/mercury/examples/input/input.vue, packages/mercury/src/input/input.js, packages/mercury/src/input/style/index.less
=> fixed input组件样式修改

packages/mercury/examples/cascader/cascader.vue, packages/mercury/examples/table/table.vue, packages/mercury/src/cascader/cascader.js, packages/mercury/src/cascader/style/index.less, packages/mercury/src/pagination/style/index.less, packages/mercury/src/table/style/index.less, packages/mercury/src/table/table.js, packages/mercury/src/theme/variable.less
Fix:table组件样式调整优化，支持表头、表体部分自定义样式。cascader 组件支持loading.
=> Fix:table组件样式调整优化，支持表头、表体部分自定义样式。cascader组件支持loading.

packages/mercury/examples/Content.vue, packages/mercury/examples/form/fd.vue, packages/mercury/examples/router.js, packages/mercury/src/form-item/form-item.js, packages/mercury/src/form-item/index.js, packages/mercury/src/form-item/style/index.js, packages/mercury/src/form-item/style/index.less, packages/mercury/src/form/form.js, packages/mercury/src/form/index.js, packages/mercury/src/form/style/index.js, packages/mercury/src/index.js, packages/mercury/src/index.less, packages/mercury/types/form-item.d.ts, packages/mercury/types/form.d.ts, packages/mercury/types/index.d.ts
=> feat 新增form组件，可以用于input加rule

packages/earth/src/picker/style/index.less
=> fix: picker组件取消按钮颜色修改#2a2a2a

packages/mercury/examples/calendar/calendar.vue, packages/mercury/src/calendar/calendar.js
=> fix:日历组件回车后input框日期显示异常

packages/mercury/examples/table/table.vue, packages/mercury/src/table/style/index.less, packages/mercury/src/table/table.js
=> feat:table新增折叠行需求开发以及其他新增优化

packages/mercury/src/table/table.js
=> fix: table监听优化以及折叠行缺陷

packages/mercury/src/table/table.js
=> fix:搜索按钮失效修复

packages/mercury/src/counter/counter.js, packages/mercury/src/counter/style/index.less
=> bug：修复ios输入框不可输入问题

packages/mercury/examples/Content.vue, packages/mercury/examples/router.js, packages/mercury/examples/switch/switch.vue, packages/mercury/src/switch/index.js, packages/mercury/src/switch/style/index.js, packages/mercury/src/switch/style/index.less, packages/mercury/src/switch/switch.js, packages/mercury/src/table/table.js
=> feat:switch组件上传

packages/mercury/src/address/address.js
=> bugfix：修复快速点击重复选择问题

packages/mercury/src/address/address.js
=> Bug fix address

packages/mercury/examples/table/table.vue, packages/mercury/src/magnifier/magnifier.js, packages/mercury/src/magnifier/style/index.less, packages/mercury/src/table/table.js
修复table组件默认选中项未初始化、magnifier图片地址异常小图列表布局出现串行、以及添加图片列表数量可控制配置
=> fix:table默认选中、magnifier组件缺陷以及优化

packages/mercury/examples/pagination/pagination.vue, packages/mercury/src/pagination/pagination.js
=> feature：分页器添加新状态

packages/earth/src/textarea/style/index.less, packages/earth/src/textarea/textarea.js
=> handleFocus

packages/mercury/src/swipe/style/index.less, packages/mercury/src/swipe/swipe.js
=> style: swipe样式优化

packages/mercury/examples/counter/counter.vue, packages/mercury/src/counter/counter.js
=> feature：优化计步器组件

packages/mercury/examples/input/input.vue, packages/mercury/src/input/input.js, packages/mercury/src/input/style/index.less, packages/mercury/src/magnifier/magnifier.js
magnifier: 添加图片缓存列表，避免多次重复loading。
input: 修复①、textarea无法传入默认值，添加disable、字数限制等功能。②、input样式优化，部分情况下样式错乱问题。
=> fix:input、magnifier组件优化

packages/mercury/src/elastic-search/elastic-search.js, packages/mercury/src/field/field.js
=> fix:elasticSearch组件input框ios换行文字替换为搜索

packages/mercury/examples/elastic-serach/elasticSearch.vue, packages/mercury/src/elastic-search/elastic-search.js, packages/mercury/src/elastic-search/style/index.less
=> feature:  elasticSearch添加插槽功能

packages/mercury/src/category-mobile/category-mobile.js, packages/mercury/src/category-mobile/style/index.less
style: category mobile  左侧样式问题修复  2.兼容ios右侧滚动事件
=> Feature category mobile style

packages/mercury/src/elastic-search/elastic-search.js
=> Hotfix elastic search

packages/mars/vue.config.js
=> fix: publicPath: "mars"

packages/mercury/examples/Content.vue, packages/mercury/examples/input/input.vue, packages/mercury/examples/router.js, packages/mercury/examples/select/select.vue, packages/mercury/src/autocomplete/autocomplete.js, packages/mercury/src/input/input.js, packages/mercury/src/option-group/index.js, packages/mercury/src/option-group/option-group.js, packages/mercury/src/option-group/style/index.js, packages/mercury/src/option-group/style/index.less, packages/mercury/src/option/index.js, packages/mercury/src/option/option.js, packages/mercury/src/option/style/index.js, packages/mercury/src/option/style/index.less, packages/mercury/src/scroller-bar/scroller-bar.js, packages/mercury/src/scroller-bar/style/index.less, packages/mercury/src/select/index.js, packages/mercury/src/select/select.js, packages/mercury/src/select/style/index.js, packages/mercury/src/select/style/index.less
1. 新增选择器（select）组件
2. input组件部分代码优化以及调整
=> feat:新增选择器（select）组件

packages/earth/src/tabs/style/index.less
=> fix: yn-tab-text, content-box

packages/mercury/examples/calendar/calendar.vue, packages/mercury/examples/form/fd.vue, packages/mercury/examples/input/input.vue, packages/mercury/examples/select/select.vue, packages/mercury/src/autocomplete/style/index.less, packages/mercury/src/calendar/calendar.js, packages/mercury/src/form-item/form-item.js, packages/mercury/src/form-item/style/index.less, packages/mercury/src/form/form.js, packages/mercury/src/input/input.js, packages/mercury/src/scroller-bar/scroller-bar.js, packages/mercury/src/select/select.js, packages/mercury/src/select/style/index.less
新增form组件以及input、calendar、select组件适配from表单的部分代码调整。
=> feat:新增form组件以及其他组件适配from组件的部分调整提交

packages/mercury/src/scroller-bar/scroller-bar.js
=> 修复ScrollerBar  ie11兼容问题

packages/mars/src/components/datePicker/datePicker.vue, packages/mars/src/components/field/field.ts, packages/mars/types/index.d.ts
=> Feature 20220414 wangsz mars fix bug

packages/mars/examples/Content.vue, packages/mars/examples/flex/flex.vue, packages/mars/examples/flex/index.ts, packages/mars/examples/router.js, packages/mars/src/components/flex-item/flex-item.ts, packages/mars/src/components/flex-item/index.ts, packages/mars/src/components/flex-item/style/index.scss, packages/mars/src/components/flex/flex.ts, packages/mars/src/components/flex/index.ts, packages/mars/src/components/flex/style/index.scss, packages/mars/src/components/mixins/slots.ts, packages/mars/src/components/select/select.vue, packages/mars/src/components/select/style/index.scss, packages/mars/src/index.ts, packages/mars/src/utils/index.ts, packages/mars/types/flex.d.ts, packages/mars/types/flexItem.ts
=> Mfeature 20220414 wangsz mars ynflex

packages/mars/examples/bootstrap.js, packages/mars/examples/iconfont/iconfont.vue, packages/mars/examples/select/select.vue, packages/mars/src/components/iconfont/iconfont.ts, packages/mars/src/components/select/select.vue, packages/mars/src/theme/variable.scss
=> Mfeature 20220418 wangsz mars fixbug

packages/mars/src/components/datePicker/basic/date-table.vue, packages/mars/src/components/datePicker/datePicker.vue, packages/mars/src/components/datePicker/panel/date-range.vue
=> Mfeature 20220421 wangsz mars fixbug

packages/mars/examples/dialog/dialog.vue, packages/mars/examples/dialog/style/index.scss, packages/mars/examples/tag/tag.vue, packages/mars/src/components/button/style/index.scss, packages/mars/src/components/dialog/dialog.vue, packages/mars/src/components/dialog/style/index.scss, packages/mars/src/components/tag/style/index.scss, packages/mars/src/components/tag/tag.ts, packages/mars/src/theme/variable.scss
=> Mfeature 20220426 wangsz mars

packages/mercury/src/autocomplete/autocomplete.js
修复:1. 输入建议下拉返回值为空时显示异常。2. 清空数据下拉选项未正确显示问题。
=> fix:修改输入建议组件空数据显示问题

packages/mercury/src/option/option.js
=> fix:修复select选项值为number类型异常情况

packages/mercury/src/scroller-bar/scroller-bar.js
=> fix:下拉框样式优化兼容select下拉框定位

packages/mars/src/components/popover/popover.vue
=> fix:popover,hover效果优化

packages/mercury/src/scroller-bar/scroller-bar.js
=> fix:下拉框底部高度不够自动向上展开

packages/earth/src/picker/pickerColumn.js
=> Feature 0701 wangsz popover visible

.gitignore, packages/earth/examples/dropdown-menu/dropdownMenu.vue, packages/earth/src/dropdown-menu-item/dropdown-menu-item.js, packages/earth/src/dropdown-menu/dropdown-menu.js, packages/earth/src/dropdown-menu/style/index.less
=> feat: dropdown-menu 添加append prop自定义内容

packages/mercury/examples/magnifier/magnifier.vue, packages/mercury/src/magnifier/magnifier.js
=> 修复magnifier组件部分在可视区域内放大时不准确问题

packages/earth/src/drawer/style/index.less
=> feat: yn-drawer-title,font-weight:600
